# Generated by Django 3.0.7 on 2020-06-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_users', '0001_initial'),
        ('accounts', '0004_auto_20200624_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='online_users.OnlineUserActivity'),
        ),
    ]
